#!/bin/bash

if [[ -n "${SOMMELIER_STRICT:-}" ]]; then
  # set -e
  set -u
fi

if [[ -n "${SOMMELIER_DEBUG:-}" ]]; then
  START=$(date +%s.%N)
  set -x
fi

if [[ "$SNAP_ARCH" != "amd64" && "$SNAP_ARCH" != "i386" ]]; then
  echo "ERROR: Host architecture ($SNAP_ARCH) unsupported."
  exit 1
fi

#####################
# Utility Functions #
#####################

# ensure_dir_exists calls `mkdir -p` if the given path is not a directory.
# This speeds up execution time by avoiding unnecessary calls to mkdir.
#
# Usage: ensure_dir_exists <path> [<mkdir-options>]...
#
ensure_dir_exists() {
  [[ -d "$1" ]] ||  mkdir -p "$@"
}

# Note: We avoid using `eval` because we don't want to expand variable names
#       in paths. For example: LD_LIBRARY_PATH paths might contain `$LIB`.
prepend_dir() {
  local -n var="$1"
  local dir="$2"
  # We can't check if the dir exists when the dir contains variables
  if [[ "$dir" == *"\$"*  || -d "$dir" ]]; then
    export "${!var}=${dir}${var:+:$var}"
  fi
}

append_dir() {
  local -n var="$1"
  local dir="$2"
  # We can't check if the dir exists when the dir contains variables
  if [[ "$dir" == *"\$"*  || -d "$dir" ]]; then
    export "${!var}=${var:+$var:}${dir}"
  fi
}

element_in() {
  local e match="$1"
  shift
  for e; do [[ "$e" == "$match" ]] && return 0; done
  return 1
}

#######################
# Sommelier functions #
#######################

init_wine() {
  echo "Initialising Wine.."

  if [[ -d "$SNAP/winedata/wine" ]]; then
    cp -urs "$SNAP/winedata/wine" "${XDG_CACHE_HOME}"
    cp -urs "$SNAP/winedata/winetricks" "${XDG_CACHE_HOME}"
  fi

  if [[ -n "${WINEARCH:-}" ]]; then
    if [[  "${WINEARCH:-}" != "win32" && "${SNAP_ARCH}" == "amd64" ]] && grep "arch=win32" "$WINEPREFIX/system.reg" >/dev/null 2>&1 ; then
        echo "WARNING: Old Wine prefix is win32, but WINEARCH is not 'win32'. Backing up old Wine prefix and generating a win64 one."
        mv "$WINEPREFIX" "${WINEPREFIX}.bak-$(date +%s)"
    elif [[ "${WINEARCH:-}" != "win64" && "${SNAP_ARCH}" == "amd64" ]] && grep "arch=win64" "$WINEPREFIX/system.reg" >/dev/null 2>&1 ; then
        echo "WARNING: Old Wine prefix is win64, but WINEARCH is not 'win64'. Backing up old Wine prefix and generating a win32 one."
        mv "$WINEPREFIX" "${WINEPREFIX}.bak-$(date +%s)"
    fi
  fi

  if [[ -n "${SOMMELIER_INSTALL_MONO:-}" ]]; then
    if [[ $(grep -c -s -e mscor -e mono "$WINEPREFIX"/user.reg) -eq 0 ]]; then
      WINE_VER=$(strings "$WINE_PLATFORM"/lib/libwine.so.1 | grep "wine-[\.0-9]" | cut -d "-" -f 2)
      MONO_VER=$(wget "https://source.winehq.org/source/dlls/appwiz.cpl/addons.c?%21v=wine-${WINE_VER}" -qO- | grep -Po 'MONO_VERSION</a>.*[0-9]"' | cut -d'"' -f4)
      if [[ $(ls "$SNAP"/wine-platform* | grep -c stable) -eq 1 ]]; then
      # For future reference see MONO_VER https://github.com/wine-mirror/wine/tree/stable of wine-stable
      case "$WINE_VER" in
      3.0.4)
        MONO_VER="4.7.1"
        ;;

      4.0.3)
        MONO_VER="4.7.5"
        ;;

      5.0.3)
        MONO_VER="4.9.4"
        ;;

      6.0.1|6.0.2|6.0.3|6.0.4)
        MONO_VER="5.1.1-x86"
        ;;

      7.0|7.0.0|7.0.0.0)
        MONO_VER="7.0.0-x86"
        ;;
      esac
    else
      if [[ ! $(echo "$WINE_VER<5.18"|bc) -gt 0 ]]; then
        MONO_VER="$MONO_VER-x86"
      fi
    fi
      MONO_URL="https://dl.winehq.org/wine/wine-mono/$(cut -d'-' -f1 <<< ${MONO_VER})/wine-mono-${MONO_VER}.msi"
      # If we've been given an installer URL derive the filename
      MONO_MSI="$(basename "${MONO_URL//\?*/}")"
      # Create wine cache dir
      ensure_dir_exists "${XDG_CACHE_HOME}"/wine
      # Download Wine Mono to cache
      if [[ ! -f "${XDG_CACHE_HOME}/wine/${MONO_MSI}" ]]; then
        wget "${MONO_URL}" -O "${XDG_CACHE_HOME}/wine/${MONO_MSI}" 2>&1 | \
        perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
        yad --progress --title="Downloading ${MONO_MSI}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape 2&>/dev/null
      fi
    fi
  fi

  # Create the Wineprefix
  "${WINELOADER}" wineboot --init 2>&1 | \
  yad --progress --title="Preparing Windows compatibility layer" --progress-text= --width=400 --center --no-buttons --auto-close --auto-kill --pulsate 2&>/dev/null
  # Opt out of winetricks metrics - we ninja this to avoid dialogs
  if [[ ! -f "${XDG_CACHE_HOME}/winetricks/track_usage" ]]; then
    mkdir -p "${XDG_CACHE_HOME}/winetricks"
    echo 0 > "${XDG_CACHE_HOME}/winetricks/track_usage"
  fi

  if [[ -L "${WINEPREFIX}/drive_c/users/$USER/Downloads" && -d "${WINEPREFIX}/drive_c/users/$USER/Downloads" ]]; then
    find "${WINEPREFIX}/drive_c/users/$USER" -type l -name Downloads | xargs rm 2>/dev/null
    source "$XDG_CONFIG_HOME/user-dirs.dirs"
    ln -s "$XDG_DOWNLOAD_DIR" "${WINEPREFIX}/drive_c/users/$USER/"
  fi

  # link ttf & ttc fonts from root to wineprefix
  ensure_dir_exists "$WINEPREFIX/drive_c/windows/Fonts"
  find /usr/share/fonts/ -type f \( -name "*.ttf" -o -name "*.ttc" \) -exec ln -vs "{}" "$WINEPREFIX/drive_c/windows/Fonts/" \; &>/dev/null

  if [[ -z "${SOMMELIER_NO_THEME:-}" ]]; then
    # Install Zhiyi's light theme and set as default
    ensure_dir_exists "$WINEPREFIX/drive_c/windows/Resources/Themes/light"
    cp -r "$SNAP/sommelier/themes/"* "$WINEPREFIX/drive_c/windows/Resources/Themes"
    "$WINELOADER" regedit "$SNAP/sommelier/themes/light/light.reg"
    sleep 1
  fi

  # Better support for Chinese fonts.
  if (locale | grep 'LANG=ja_JP') >/dev/null 2>&1; then
    "$WINELOADER" regedit "$SNAP/sommelier/config/noto-sans-cjk-jp.reg"
    sleep 1
  elif (locale | grep 'LANG=ko_KR') >/dev/null 2>&1; then
    "$WINELOADER" regedit "$SNAP/sommelier/config/noto-sans-cjk-kr.reg"
    sleep 1
  elif (locale | grep -e 'LANG=zh_CN' -e 'LANG=zh_SG') >/dev/null 2>&1; then
    "$WINELOADER" regedit "$SNAP/sommelier/config/noto-sans-cjk-sc.reg"
    sleep 1
  elif (locale | grep 'LANG=zh_HK') >/dev/null 2>&1; then
    "$WINELOADER" regedit "$SNAP/sommelier/config/noto-sans-cjk-hk.reg"
    sleep 1
  elif (locale | grep -e 'LANG=zh_MO' -e 'LANG=zh_TW') >/dev/null 2>&1; then
    "$WINELOADER" regedit "$SNAP/sommelier/config/noto-sans-cjk-tc.reg"
    sleep 1
  fi
  echo "$SNAP_REVISION" > "$SNAP_USER_COMMON/.last_snap_revision"
}

install_app() {
  echo "Installing application.."

  # Install additional requirements via winetricks
  if [[ -n "${TRICKS:-}" ]]; then
    for TRICK in ${TRICKS}; do
      "${WINETRICKS}" --unattended "${TRICK}" | \
      yad --progress --title="Installing ${TRICK}" --progress-text= --width=400 --center --no-buttons --auto-close --auto-kill --on-top --pulsate 2&>/dev/null
    done
  fi

  # Run pre-install hook
  if [[ -f "$SNAP/sommelier/hooks/pre-install" ]]; then
    echo "Running hook '$SNAP/sommelier/hooks/pre-install'"
    . "$SNAP/sommelier/hooks/pre-install"
  fi

  ORIGINAL_LINKS=( "$(xdg-user-dir DESKTOP)"/*.lnk )

  # Download installer if requested.
  if [[ -n "${INSTALL_URL:-}" ]]; then
    # If we've been given an installer URL derive the filename
    INSTALL_EXE="$(basename "${INSTALL_URL//\?*/}")"

    wget "${INSTALL_URL}" -O "${TMPDIR}/${INSTALL_EXE}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress --title="Downloading ${INSTALL_EXE}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape 2&>/dev/null

    LOCAL_INSTALL_EXE="${TMPDIR}/${INSTALL_EXE}"
  elif [[ -n "${INSTALL_EXE:-}" ]]; then
    LOCAL_INSTALL_EXE="${INSTALL_EXE}"
  fi

  # Install the application in Wine
  if [[ -n "${LOCAL_INSTALL_EXE:-}" ]]; then
    # Convert INSTALL_FLAGS to an array to support multiple quoted arguments.
    # https://stackoverflow.com/a/37381300/1588555
    IFS=$'\n' ARR_INSTALL_FLAGS=( $(xargs -n1 <<<"${INSTALL_FLAGS:-}") )
    # Piping the wine command to yad gives weird behavior, so instead we use
    # yad in the background and kill it after the installation finishes.
    EXE_NAME=$(basename "${LOCAL_INSTALL_EXE}")
    yes | yad --progress --title="Installing ${EXE_NAME}" --progress-text= --width=400 --center --no-buttons --auto-close --auto-kill --on-top --pulsate &
    INSTALL_YAD_PID="$!"
    "${WINELOADER}" "${LOCAL_INSTALL_EXE}" "${ARR_INSTALL_FLAGS[@]}"
    kill "$INSTALL_YAD_PID"
  fi

  # Remove the cached installer
  if [[ -n "${INSTALL_URL:-}" ]]; then
    rm -v "${TMPDIR}/${INSTALL_EXE}"
  fi

  # Run post-install hook
  if [[ -f "$SNAP/sommelier/hooks/post-install" ]]; then
    echo "Running hook '$SNAP/sommelier/hooks/post-install'"
    . "$SNAP/sommelier/hooks/post-install"
  fi

  # Remove any Windows shortcuts the installer created since these don't work
  # in Linux and some users get confused by them.
  for CURRENT_LINK in "$(xdg-user-dir DESKTOP)"/*.lnk; do
    element_in "$CURRENT_LINK" "${ORIGINAL_LINKS[@]}" || rm "$CURRENT_LINK"
  done

  echo "$SNAP_VERSION" > "$SNAP_USER_COMMON/.last_snap_version"
}

start_app() {
  echo "Starting application.."

  if [[ -f "$SNAP/sommelier/hooks/pre-start" ]]; then
    echo "Running hook '$SNAP/sommelier/hooks/pre-start'"
    . "$SNAP/sommelier/hooks/pre-start"
  fi

  # Convert all arguments which point to existing files/dirs to Windows paths.
  for i in "${ACTION_ARGS[@]}"; do
    if [[ -e "${i}" ]]; then
      args+=( "$(winepath -w "$i")" )
    else
      args+=( "$i" )
    fi
  done
  ACTION_ARGS=( "${args[@]}" )

  if [[ -n "${SOMMELIER_DEBUG:-}" ]]; then
    echo "DEBUG: Sommelier elapsed time: $(date +%s.%N --date="$START seconds ago")"
    echo "DEBUG: Now running: '${WINELOADER}' '${RUN_EXE}' '${ACTION_ARGS[@]}'"
  fi

  # Because Windows software will often look for program files in the location
  # they were started from we need to start it in a very specific way: change
  # directory to the folder where the program is located and run the .exe file
  # using _only_ its filename.
  if [[ -z "${SOMMELIER_KEEP_CWD:-}" ]]; then
    app_dir=$(dirname "${RUN_EXE}")
    app=$(basename "${RUN_EXE}")
    cd "${app_dir}"
  else
    app="${RUN_EXE}"
  fi

  # Note 1: We use `wine` because `wine start \wait \unix` has problems with
  #         relative unix-style paths.
  # Note 2: `wine` already waits until the program exits, so we don't need to
  #          manually wait here.
  # Note 3: If requested, we run the app in a new virtual desktop. This can
  #         elimitate bugs with alt-tab and fullscreen on XWayland.
  if [[ -n "${SOMMELIER_VIRTDESKTOP:-}" ]]; then
    local native_res
    if [[ "${XDG_SESSION_TYPE}" == "x11" ]]; then
      native_res=$(xrandr -q | grep primary | cut -d' ' -f4 | cut -d'+' -f1)
    else
      # Wayland doesn't have a "primary display". We use the biggest screen
      # instead.
      native_res=$(xrandr -q | grep XWAYLAND | cut -d' ' -f3 | cut -d'+' -f1 | sort -r -n | sort -r -n | head -n 1)
    fi
    "${WINELOADER}" explorer /desktop="virtual","${native_res}" "${app}" "${ACTION_ARGS[@]}"
    local exit_code="$?"
  else
    "${WINELOADER}" "${app}" "${ACTION_ARGS[@]}"
    local exit_code="$?"
  fi

  if [[ -f "$SNAP/sommelier/hooks/post-stop" ]]; then
    echo "Running hook '$SNAP/sommelier/hooks/post-stop'"
    . "$SNAP/sommelier/hooks/post-stop"
  fi

  exit $exit_code
}

if [[ -z "${WINEDEBUG:-}" ]]; then
  export WINEDEBUG="-all"
fi

if [[ ! -f "${WINEPREFIX}/drive_c/windows/system.ini"  || "$(cat "$SNAP_USER_COMMON/.last_snap_revision" 2>/dev/null)" != "$SNAP_REVISION" ]]; then
  init_wine
fi


#####################################
# Actually run the requested action #
#####################################

# Get the action we're asked to run
if [[ -n "${1:-}" ]]; then
  ACTION="${1}"
  shift
  ACTION_ARGS=( "$@" )
else
  echo "ERROR: I need an action as first argument. Exiting here."
  exit 1
fi

# Start the requested program.
if [[ "$ACTION" = "winetricks" ]]; then
  "$WINETRICKS" "${ACTION_ARGS[@]}"
elif [[ "$ACTION" = "winedbg" ]]; then
  "$ACTION" "${ACTION_ARGS[@]}"
elif [[ "$ACTION" = "run-exe" ]]; then
  # Check if we know which executable to run.
  # Note: RUN_EXE is provided as an environment variable instead of a CLI
  # parameter so that snaps using command-chain can specify an executable
  # with a space in the path without having to use a wrapper script.
  if [[ -z "${RUN_EXE:-}" ]]; then
    echo "ERROR: No executable provided. Please provide the path to the executable using the RUN_EXE environment variable."
    exit 1
  fi

  if [[ "$SNAP_ARCH" == "i386" ]]; then
    RUN_EXE="${RUN_EXE/Program Files (x86)/Program Files}"
  fi

  # Convert Windows path to unix
  RUN_EXE=$("$WINELOADER" winepath "$RUN_EXE")

  # Install if the executable doesn't exist or the snap version changed.
  if [[ ! -e "$RUN_EXE"  || "$(cat "$SNAP_USER_COMMON/.last_snap_version" 2>/dev/null)" != "$SNAP_VERSION" ]]; then
    install_app
  fi

  # Run the application
  start_app
else
  "$WINELOADER" "$ACTION" "${ACTION_ARGS[@]}"
fi
